version: "3"

services:
  # container del backend del microservizio tasse
  taxBE:
    image: openjdk:17-jdk-alpine
    container_name: taxBE
    ports:
      - "8080:8080"
      - "8002:8000"
    expose:
      - "8002"
    depends_on:
      - taxDB
    networks:
      - taxNetwork
    volumes:
      - ./build/libs/TaxBE-0.0.1-SNAPSHOT.jar:/app/app.jar
    working_dir: /app
    entrypoint: java -Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000 -jar /app/app.jar

  # container del database del microservizio
  taxDB:
    image: mongo:5.0
    container_name: taxDB
    ports:
      - "27018:27017"
    volumes:
      - ./mongodb_data:/data/db
    networks:
      - taxNetwork

# rete interna del microservizio
networks:
  taxNetwork:
    driver:
      "bridge"