version: "3"

services:
  taxBE:
    image: openjdk:17-jdk-alpine
    container_name: taxBE
    ports:
      - "8082:8080"
      - "8002:8000"
    expose:
      - "8002"
    depends_on:
      - taxDB
    networks:
      - taxNetwork
    volumes:
      - ./build/libs/TaxBE-0.0.1-SNAPSHOT.jar:/app/app.jar
    working_dir: /app
    entrypoint: java -Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000 -jar /app/app.jar

  taxDB:
    image: mongo:5.0
    container_name: taxDB
    ports:
      - "27019:27017"
    networks:
      - taxNetwork

networks:
  taxNetwork:
    driver:
      "bridge"