/**
 * Data Transfer Object (DTO) representing Waste Statistics information.
 * This DTO is used to transfer statistics related to waste generation by users between different parts of the application.
 */
package it.unisalento.pas.taxbe.dto;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * A DTO class that encapsulates statistics related to waste generation by a user for a specific year.
 */
@NoArgsConstructor
@Getter
@Setter
public class WasteStatisticsDTO {
    /**
     * The user ID associated with the waste statistics.
     */
    String userId;

    /**
     * The year for which the waste statistics are recorded.
     */
    int year;

    /**
     * The total amount of sorted waste generated by the user in the specified year.
     */
    int totalSortedWaste;

    /**
     * The total amount of unsorted waste generated by the user in the specified year.
     */
    int totalUnsortedWaste;
}
